export const CCQ_SECTORS = [
    'Génie civil : Aqueducs et égouts',
    'Génie civil : Gazoducs et oléoducs',
    'Génie civil : Lignes de transport d\'énergie',
    'Génie civil : Ponts et viaducs',
    'Génie civil : Voirie et pavage',
    'Génie civil : Autre',
    'Institutionnel',
    'Commercial',
    'Industriel lourd',
    'Industriel léger',
    'Résidentiel léger',
    'Résidentiel lourd'
];

export const CCQ_TRADES = [
    '110 - Briqueteur-maçon',
    '130 - Calorifugeur',
    '140 - Carreleur',
    '160 - Charpentier-menuisier',
    '190 - Chaudronnier',
    '200 - Cimentier-applicateur',
    '210 - Couvreur',
    '220 - Électricien',
    '230 - Ferblantier',
    '240 - Ferrailleur',
    '250 - Grutier',
    '270 - Mécanicien d\'ascenseur',
    '280 - Mécanicien de chantier',
    '290 - Mécanicien de machinerie lourde',
    '304 - Monteur-assembleur',
    '310 - Monteur-mécanicien (vitrier)',
    '338 - Opérateur d\'équipement lourd',
    '340 - Opérateur de pelles mécaniques',
    '350 - Peintre',
    '370 - Plâtrier',
    '380 - Poseur de systèmes intérieurs',
    '390 - Poseur de revêtements souples',
    '400 - Serrurier de bâtiment',
    '410 - Tuyauteur',
    '412 - Plombier',
    '414 - Mécanicien en protection-incendie',
    '418 - Frigoriste',
    '617 - Boutefeu / Foreur',
    '713 - Manœuvre',
    '722 - Arpenteur',
    '761 - Soudeur',
    '763 - Soudeur de machinerie lourde',
    'Apprenti',
    'Intervenant en chantier',
    'Intervenant environnemental',
    'Intervenant technique',
    'Non applicable (Hors-décret)'
];
