export const CCQ_SECTORS = [
    'Génie civil et voirie',
    'Institutionnel et commercial',
    'Industriel',
    'Résidentiel'
];

export const CCQ_TRADES = [
    'Apprenti',
    'Boutefeu / Foreur',
    'Calorifugeur',
    'Carreleur',
    'Charpentier-menuisier',
    'Chaudronnier',
    'Cimentier-applicateur',
    'Couvreur',
    'Électricien',
    'Ferblantier',
    'Ferrailleur',
    'Frigoriste',
    'Grutier',
    'Installateur de revêtements souples',
    'Intervenant en chantier',
    'Intervenant environnemental',
    'Intervenant technique',
    'Maçon',
    'Manœuvre',
    'Mécanicien d\'ascenseur',
    'Mécanicien de chantier',
    'Mécanicien de machinerie lourde',
    'Mécanicien en protection-incendie',
    'Monteur-assembleur',
    'Opérateur d\'équipement lourd',
    'Opérateur de pelles',
    'Peintre',
    'Plâtrier',
    'Plombier',
    'Serrurier de bâtiment',
    'Soudeur',
    'Soudeur en tuyauterie',
    'Tôlier',
    'Tuyauteur',
    'Non applicable (Hors-décret)'
];
